### ISSUE TITLE
Upload a file to nextcloud via Website

### ISSUE THREAD

**Issue by tailoric** [amosproj/amos2021ws03-teams-to-nextcloud#2]
## User story
1. As a user
2. I want to upload files to nextcloud
3. So that I add files from the website view

## Acceptance criteria
* depends on #3 
* Button or Field for file upload exist
* drag and drop or file upload dialog by the browser for selecting the file to upload 
* file is stored inside the nextcloud account

## Definition of done
* Added only after week 5

**Comment by rbalink** [comment]
Its implemented
