### ISSUE TITLE
Basic first webview for Teams tab

### ISSUE THREAD

**Issue by tailoric** [amosproj/amos2021ws03-teams-to-nextcloud#4]
## User story
1. As a developer
2. I need a Tab Add-on running in Teams added to a Teams Channel
3. So that I can add my Nextcloud frontend later

## Acceptance criteria
* Have a Tab App running inside a Teams instance
* It should be linked to a Team Channel ![Teams channel tabs](https://user-images.githubusercontent.com/16943959/140085413-2a69faae-7624-460c-80ed-afc28b7e8d1e.png)
* Show the basic hello world example or any content of the frontend

## Definition of done
* Added only after week 5
* The same for all features

**Comment by rbalink** [comment]
Overlapping #8
