### ISSUE TITLE
Show Basic User Information in Teams App Tab

### ISSUE THREAD

**Issue by tailoric** [amosproj/amos2021ws03-teams-to-nextcloud#5]
## User story
1. As a developer
2. I want information about the user and the channel
3. So that I can later link them to the nextcloud server files

## Acceptance criteria
* Display username and user avatar on the teams app tab
* Display the current channel / team on the app tab

## Definition of done
- [x] Code is reviewed and merged to main by RM (or at least a different person from the one, who has implemented it)
- [x] The code builds without errors or if there are any - they are noted down and clearly communicated with the team
- [x] A feature is to be implemented so that it is scalable on different devices and works consistently for the rest of the team

**Comment by rbalink** [comment]
- MicrosoftTeams Javascript client SDK ([LINK](https://docs.microsoft.com/en-us/javascript/api/overview/msteams-client?view=msteams-client-js-latest)) needs to be included in the script

calling ms sdk:
`microsoftTeams.initialize();`
`microsoftTeams.getContext(function(teamsContext){
    //relevant msTeams data }`

- relevant MS Teams Data behind the .getContext Method
- its only possible to test and check this while using the app in MS teams
- [Link](https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/microsoftteams.context?view=msteams-client-js-latest) to the .getContext properties

Example:

![](https://i.imgur.com/jzGif0I.png)

1. Name of the Team
2. Name of the Channel
3. User "Principle Name"
4. Channel ID
