### ISSUE TITLE
Better date/time representation

### ISSUE THREAD

**Issue by todormoskov** [amosproj/amos2021ws03-teams-to-nextcloud#52]
## User story
1. As a user
2. I want to have a better representation of the last modified date
3. So that my user experience is better

## Acceptance criteria
* A more user-friendly time representation should be provided for the last modified date

## Definition of done
- [x] Code is reviewed and merged to main by RM (or at least a different person from the one, who has implemented it)
- [x] The code builds without errors or if there are any - they are noted down and clearly communicated with the team
- [x] A feature is to be implemented so that it is scalable on different devices and works consistently for the rest of the team

**Comment by tailoric** [comment]
A more user-friendly time representation is very subjective criteria
not sure what I should do if I got that ticket
