### ISSUE TITLE
Create a basic Project Skeleton

### ISSUE THREAD

**Issue by tailoric** [amosproj/amos2021ws03-teams-to-nextcloud#8]
## User story
1. As a developer
2. I need a basic file structure of our project
3. So that we can organize our project efficiently

## Acceptance criteria
* Have a basic functional teams app setup inside the repository see #4 
* Have our frontend files and node server inside the repository for displaying our pages later for teams

## Definition of done
* Added only after week 5
* The same for all features

**Comment by rbalink** [comment]
Its implemented
