### ISSUE TITLE
Github page documentation

### ISSUE THREAD

**Issue by rbalink** [amosproj/amos2021ws03-teams-to-nextcloud#84]
## User story
1. As an administrator
2. I want to have a guide / manual which provides all important information about the app
3. So that I can understand how the app works 

## Acceptance criteria
* Github page is created
* Guide provides information about the initial setup: installing the zip file, setting it up on teams and information about the configuration of the server (reference https://github.com/amosproj/amos2021ws03-teams-to-nextcloud/tree/main/Documentation)

## Definition of done
- [ ] Code is reviewed and merged to main by RM (or at least a different person from the one, who has implemented it)
- [ ] The code builds without errors or if there are any - they are noted down and clearly communicated with the team
- [ ] A feature is to be implemented so that it is scalable on different devices and works consistently for the rest of the team
- [ ] The code goes successfully through the CI pipeline

**Comment by Smoothex** [comment]
GitHub Pages article has been created [here](https://amosproj.github.io/amos2021ws03-teams-to-nextcloud/). Real size has been communicated with assignees, closing the ticket.
